name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build static site with Docker
        run: |
          # Build the "builder" stage of the Dockerfile, passing the subpath as a build arg. Default is /. Added for Github pages deploy
          docker build \
            --target builder \
            --build-arg VITE_BASE_PATH=/zotero-bulk-importer/ \
            -t static-builder \
            -f Dockerfile.static .
          
          # Create a temporary container to extract the files
          docker create --name extractor static-builder
          
          # Copy the generated folder to the host
          docker cp extractor:/app/dist/client ./dist-site
          
          # Clean up the container
          docker rm extractor

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist-site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
